### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by vweevers** [Level/lazy-open#42]
- [x] Disable Greenkeeper
- [x] Make sure the latest published version is git-tagged
- [x] Add note to readme (example: https://github.com/Level/level-mobile/pull/22)
- [x] Remove project from Travis
- [x] Pin dependencies
- [x] Release a final patch version
- [x] Deprecate the package with `This project has been abandoned. There will be no further releases. If you wish to revive level-lazy-open, please open an issue (https://github.com/Level/community) to discuss a way forward. Thank you!`
- [x] Remove extraneous npm owners
- [x] Archive the GitHub repository

--

This module has 0 (public) dependents on npm and close to 0 downloads:

![image](https://user-images.githubusercontent.com/3055345/51073991-2f2f6580-1679-11e9-9867-41466f5fc61a.png)

**Comment by ralphtheninja** [comment]
Yep, lets archive it!

**Comment by vweevers** [comment]
Oh, I forgot (https://github.com/Level/community/issues/43#issuecomment-478332361) I opened this 😄
